//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.CLI.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.CLI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access Denied. Please restart your shell as Administrator to run the &apos;{0}&apos; command..
        /// </summary>
        public static string Msg_AdminPrivilegesRequired {
            get {
                return ResourceManager.GetString("Msg_AdminPrivilegesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation &apos;{0}&apos; was cancelled by the user..
        /// </summary>
        public static string Msg_CommandCancelled {
            get {
                return ResourceManager.GetString("Msg_CommandCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to {0}: {1}.
        /// </summary>
        public static string Msg_CommandFailedTemplate {
            get {
                return ResourceManager.GetString("Msg_CommandFailedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à export configuration for service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_ExportServiceAction {
            get {
                return ResourceManager.GetString("Msg_ExportServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensure the service exists in the database and you have write permissions to the destination path..
        /// </summary>
        public static string Msg_ExportServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_ExportServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} configuration exported successfully to: {1}.
        /// </summary>
        public static string Msg_ExportSuccess {
            get {
                return ResourceManager.GetString("Msg_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service configuration was imported, but failed to deserialize for installation..
        /// </summary>
        public static string Msg_ImportDeserializationFailure {
            get {
                return ResourceManager.GetString("Msg_ImportDeserializationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} file is not valid: {1}.
        /// </summary>
        public static string Msg_ImportFormatInvalid {
            get {
                return ResourceManager.GetString("Msg_ImportFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service configuration was saved, but installation failed for service &apos;{0}&apos;..
        /// </summary>
        public static string Msg_ImportInstallGeneralFailure {
            get {
                return ResourceManager.GetString("Msg_ImportInstallGeneralFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service configuration was saved, but the service &apos;{0}&apos; could not be located for installation..
        /// </summary>
        public static string Msg_ImportInstallLookupFailure {
            get {
                return ResourceManager.GetString("Msg_ImportInstallLookupFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} configuration saved and service &apos;{1}&apos; installed successfully..
        /// </summary>
        public static string Msg_ImportInstallSuccess {
            get {
                return ResourceManager.GetString("Msg_ImportInstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to import {0} configuration into the repository..
        /// </summary>
        public static string Msg_ImportRepoFailure {
            get {
                return ResourceManager.GetString("Msg_ImportRepoFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à import configuration from &apos;{0}&apos;.
        /// </summary>
        public static string Msg_ImportServiceAction {
            get {
                return ResourceManager.GetString("Msg_ImportServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check that the file path is correct, the file format is valid JSON or XML, and you have read permissions..
        /// </summary>
        public static string Msg_ImportServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_ImportServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} configuration imported successfully..
        /// </summary>
        public static string Msg_ImportSuccessNoInstall {
            get {
                return ResourceManager.GetString("Msg_ImportSuccessNoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à install service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_InstallServiceAction {
            get {
                return ResourceManager.GetString("Msg_InstallServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensure the executable path is correct, the service name is not already in use, and you are running with Administrator privileges..
        /// </summary>
        public static string Msg_InstallServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_InstallServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service &apos;{0}&apos; installed successfully..
        /// </summary>
        public static string Msg_InstallSuccess {
            get {
                return ResourceManager.GetString("Msg_InstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration file type is required (XML or JSON)..
        /// </summary>
        public static string Msg_InvalidConfigFileType {
            get {
                return ResourceManager.GetString("Msg_InvalidConfigFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid value for {0}: &apos;{1}&apos;. Valid options: {2}.
        /// </summary>
        public static string Msg_InvalidEnumValue {
            get {
                return ResourceManager.GetString("Msg_InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid executable path: {0}. Ensure the file exists and is accessible..
        /// </summary>
        public static string Msg_InvalidExecutablePath {
            get {
                return ResourceManager.GetString("Msg_InvalidExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid integer format for {0}: &apos;{1}&apos;.
        /// </summary>
        public static string Msg_InvalidIntegerFormat {
            get {
                return ResourceManager.GetString("Msg_InvalidIntegerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid {0} in configuration. Ensure the path exists and is accessible..
        /// </summary>
        public static string Msg_InvalidPathInConfig {
            get {
                return ResourceManager.GetString("Msg_InvalidPathInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File path is required..
        /// </summary>
        public static string Msg_PathRequired {
            get {
                return ResourceManager.GetString("Msg_PathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparing environment....
        /// </summary>
        public static string Msg_PreparingEnvironment {
            get {
                return ResourceManager.GetString("Msg_PreparingEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à restart service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_RestartServiceAction {
            get {
                return ResourceManager.GetString("Msg_RestartServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensure the service is currently installed and that your account has sufficient permissions to stop and start services..
        /// </summary>
        public static string Msg_RestartServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_RestartServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service &apos;{0}&apos; restarted successfully..
        /// </summary>
        public static string Msg_RestartSuccess {
            get {
                return ResourceManager.GetString("Msg_RestartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified service is disabled..
        /// </summary>
        public static string Msg_ServiceDisabledError {
            get {
                return ResourceManager.GetString("Msg_ServiceDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service name is required..
        /// </summary>
        public static string Msg_ServiceNameRequired {
            get {
                return ResourceManager.GetString("Msg_ServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified service was not found..
        /// </summary>
        public static string Msg_ServiceNotFound {
            get {
                return ResourceManager.GetString("Msg_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à query status for service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_ServiceStatusAction {
            get {
                return ResourceManager.GetString("Msg_ServiceStatusAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service status for &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Msg_ServiceStatusResult {
            get {
                return ResourceManager.GetString("Msg_ServiceStatusResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify the service name is spelled correctly and that it is currently installed on this system..
        /// </summary>
        public static string Msg_ServiceStatusSuggestion {
            get {
                return ResourceManager.GetString("Msg_ServiceStatusSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à start service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_StartServiceAction {
            get {
                return ResourceManager.GetString("Msg_StartServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensure the service is installed, the executable path is valid, and the service account has &apos;Log On As Service&apos; rights..
        /// </summary>
        public static string Msg_StartServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_StartServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service &apos;{0}&apos; started successfully..
        /// </summary>
        public static string Msg_StartSuccess {
            get {
                return ResourceManager.GetString("Msg_StartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à stop service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_StopServiceAction {
            get {
                return ResourceManager.GetString("Msg_StopServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensure you have Administrator privileges. If the service is unresponsive, you may need to terminate the process manually via Task Manager..
        /// </summary>
        public static string Msg_StopServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_StopServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service &apos;{0}&apos; stopped successfully..
        /// </summary>
        public static string Msg_StopSuccess {
            get {
                return ResourceManager.GetString("Msg_StopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suggestion: {0}.
        /// </summary>
        public static string Msg_SuggestionTemplate {
            get {
                return ResourceManager.GetString("Msg_SuggestionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à uninstall service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_UninstallServiceAction {
            get {
                return ResourceManager.GetString("Msg_UninstallServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensure the service is stopped before uninstalling and that you are running this command as an Administrator..
        /// </summary>
        public static string Msg_UninstallServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_UninstallServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service &apos;{0}&apos; uninstalled successfully..
        /// </summary>
        public static string Msg_UninstallSuccess {
            get {
                return ResourceManager.GetString("Msg_UninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unknown error occurred..
        /// </summary>
        public static string Msg_UnknownError {
            get {
                return ResourceManager.GetString("Msg_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsupported configuration file type: {0}.
        /// </summary>
        public static string Msg_UnsupportedFileType {
            get {
                return ResourceManager.GetString("Msg_UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrapper executable not found at: %ProgramData%\Servy\Servy.Service.CLI.exe. Ensure Servy is properly installed..
        /// </summary>
        public static string Msg_WrapperNotFound {
            get {
                return ResourceManager.GetString("Msg_WrapperNotFound", resourceCulture);
            }
        }
    }
}
