//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All files (*.*)|*.*.
        /// </summary>
        public static string FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executable files (*.exe)|*.exe|All files (*.*)|*.*.
        /// </summary>
        public static string FileFilter_Executable {
            get {
                return ResourceManager.GetString("FileFilter_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON files (*.json)|*.json.
        /// </summary>
        public static string FileFilter_Json {
            get {
                return ResourceManager.GetString("FileFilter_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML files (*.xml)|*.xml.
        /// </summary>
        public static string FileFilter_Xml {
            get {
                return ResourceManager.GetString("FileFilter_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrator privileges are required..
        /// </summary>
        public static string Msg_AdminRightsRequired {
            get {
                return ResourceManager.GetString("Msg_AdminRightsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arguments for field &apos;{0}&apos; exceed the Windows command-line limit of {1} characters..
        /// </summary>
        public static string Msg_ArgumentsLengthReachedForField {
            get {
                return ResourceManager.GetString("Msg_ArgumentsLengthReachedForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration file &apos;{0}&apos; exceeds maximum size ({1} MB)..
        /// </summary>
        public static string Msg_ConfigSizeLimitReached {
            get {
                return ResourceManager.GetString("Msg_ConfigSizeLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dependency &apos;{0}&apos; is not accessible (Access Denied)..
        /// </summary>
        public static string Msg_DependencyAccessDenied {
            get {
                return ResourceManager.GetString("Msg_DependencyAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dependency &apos;{0}&apos; is unavailable..
        /// </summary>
        public static string Msg_DependencyUnavailable {
            get {
                return ResourceManager.GetString("Msg_DependencyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description exceeds {0} characters..
        /// </summary>
        public static string Msg_DescriptionLengthReached {
            get {
                return ResourceManager.GetString("Msg_DescriptionLengthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display name exceeds {0} characters..
        /// </summary>
        public static string Msg_DisplayNameLengthReached {
            get {
                return ResourceManager.GetString("Msg_DisplayNameLengthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Environment variable &apos;{0}&apos; contains a forbidden newline character. Multi-line values are not supported..
        /// </summary>
        public static string Msg_EnvironmentVariableForbiddenNewline {
            get {
                return ResourceManager.GetString("Msg_EnvironmentVariableForbiddenNewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Environment variable key cannot be empty..
        /// </summary>
        public static string Msg_EnvironmentVariableKeyEmpty {
            get {
                return ResourceManager.GetString("Msg_EnvironmentVariableKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The environment variable key &apos;{0}&apos; contains illegal characters..
        /// </summary>
        public static string Msg_EnvironmentVariableKeyInvalidChars {
            get {
                return ResourceManager.GetString("Msg_EnvironmentVariableKeyInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each environment variable must contain an unescaped &apos;=&apos; character to separate the key from the value..
        /// </summary>
        public static string Msg_EnvironmentVariableMissingEquals {
            get {
                return ResourceManager.GetString("Msg_EnvironmentVariableMissingEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service process path cannot be empty..
        /// </summary>
        public static string Msg_ExecutablePathRequired {
            get {
                return ResourceManager.GetString("Msg_ExecutablePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A fatal error occurred and the application must close. Detailed diagnostics have been saved to the log file..
        /// </summary>
        public static string Msg_FatalError_Body {
            get {
                return ResourceManager.GetString("Msg_FatalError_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Servy - Fatal Error.
        /// </summary>
        public static string Msg_FatalError_Title {
            get {
                return ResourceManager.GetString("Msg_FatalError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} deserialization resulted in an empty service definition..
        /// </summary>
        public static string Msg_ImportEmptyDefinition {
            get {
                return ResourceManager.GetString("Msg_ImportEmptyDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Import] File not found: {0}.
        /// </summary>
        public static string Msg_ImportFileNotFound {
            get {
                return ResourceManager.GetString("Msg_ImportFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} input cannot be empty or whitespace..
        /// </summary>
        public static string Msg_ImportInputEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("Msg_ImportInputEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid {0} structure: {1}.
        /// </summary>
        public static string Msg_ImportInvalidStructure {
            get {
                return ResourceManager.GetString("Msg_ImportInvalidStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} payload exceeds the maximum allowed size of {1} MB..
        /// </summary>
        public static string Msg_ImportPayloadTooLarge {
            get {
                return ResourceManager.GetString("Msg_ImportPayloadTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} structure error: {1}.
        /// </summary>
        public static string Msg_ImportStructureError {
            get {
                return ResourceManager.GetString("Msg_ImportStructureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified date rotation type is invalid. Options: Daily, Weekly, Monthly..
        /// </summary>
        public static string Msg_InvalidDateRotationType {
            get {
                return ResourceManager.GetString("Msg_InvalidDateRotationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The failure program path is invalid..
        /// </summary>
        public static string Msg_InvalidFailureProgramPath {
            get {
                return ResourceManager.GetString("Msg_InvalidFailureProgramPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified failure program startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidFailureProgramStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidFailureProgramStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heartbeat interval must be a number of seconds between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidHeartbeatInterval {
            get {
                return ResourceManager.GetString("Msg_InvalidHeartbeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max Failed Checks must be a number between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidMaxFailedChecks {
            get {
                return ResourceManager.GetString("Msg_InvalidMaxFailedChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max Restart Attempts must be a number between {0} and {1}. Set to 0 for unlimited restart attempts..
        /// </summary>
        public static string Msg_InvalidMaxRestartAttempts {
            get {
                return ResourceManager.GetString("Msg_InvalidMaxRestartAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max rotations must be a number between {0} and {1}. Set to 0 for unlimited rotations..
        /// </summary>
        public static string Msg_InvalidMaxRotations {
            get {
                return ResourceManager.GetString("Msg_InvalidMaxRotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified path is invalid..
        /// </summary>
        public static string Msg_InvalidPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The post-launch process path is invalid..
        /// </summary>
        public static string Msg_InvalidPostLaunchPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPostLaunchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified post-launch startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidPostLaunchStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidPostLaunchStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The post-stop process path is invalid..
        /// </summary>
        public static string Msg_InvalidPostStopPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPostStopPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified post-stop startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidPostStopStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidPostStopStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The pre-launch process path is invalid..
        /// </summary>
        public static string Msg_InvalidPreLaunchPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pre-Launch retry attempts must be a number between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidPreLaunchRetryAttempts {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchRetryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified pre-launch startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidPreLaunchStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified pre-launch stderr file path is invalid..
        /// </summary>
        public static string Msg_InvalidPreLaunchStderrPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchStderrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified pre-launch stdout file path is invalid..
        /// </summary>
        public static string Msg_InvalidPreLaunchStdoutPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchStdoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pre-Launch timeout must be a number of seconds between {0} and {1}. Set the timeout to 0 to run the pre-launch hook in fire-and-forget mode. When set to 0, the hook is started and the service is launched immediately without waiting for completion. Use fire-and-forget only for tasks that do not affect the service&apos;s ability to start or run correctly. Stdout/Stderr redirection and retries are not available in fire-and-forget mode..
        /// </summary>
        public static string Msg_InvalidPreLaunchTimeout {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The pre-stop process path is invalid..
        /// </summary>
        public static string Msg_InvalidPreStopPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPreStopPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified pre-stop startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidPreStopStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidPreStopStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pre-Stop timeout must be a number of seconds between {0} and {1}. Set the timeout to 0 to run the pre-stop process in fire-and-forget mode..
        /// </summary>
        public static string Msg_InvalidPreStopTimeout {
            get {
                return ResourceManager.GetString("Msg_InvalidPreStopTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified process priority is invalid. Options: Idle, BelowNormal, Normal, AboveNormal, High, RealTime..
        /// </summary>
        public static string Msg_InvalidProcessPriority {
            get {
                return ResourceManager.GetString("Msg_InvalidProcessPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified recovery action is invalid. Options: None, RestartService, RestartProcess, RestartComputer..
        /// </summary>
        public static string Msg_InvalidRecoveryAction {
            get {
                return ResourceManager.GetString("Msg_InvalidRecoveryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery actions and restart attempts cannot be configured unless --enableHealth is set to true..
        /// </summary>
        public static string Msg_InvalidRecoveryConfig {
            get {
                return ResourceManager.GetString("Msg_InvalidRecoveryConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotation size must be a number of Megabytes (MB) between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidRotationSize {
            get {
                return ResourceManager.GetString("Msg_InvalidRotationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid service name &apos;{0}&apos;. Only letters, digits, hyphens, underscores, spaces, and dollar signs ($) are allowed..
        /// </summary>
        public static string Msg_InvalidServiceDependencyName {
            get {
                return ResourceManager.GetString("Msg_InvalidServiceDependencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service name contains invalid characters. Avoid using &apos;\&apos;, &apos;/&apos;, &apos;:&apos;, &apos;*&apos;, &apos;?&apos;, &apos;&quot;&apos;, &apos;&lt;&apos;, &apos;&gt;&apos;, &apos;|&apos;..
        /// </summary>
        public static string Msg_InvalidServiceName {
            get {
                return ResourceManager.GetString("Msg_InvalidServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start timeout must be a number between {0} and {1} seconds..
        /// </summary>
        public static string Msg_InvalidStartTimeout {
            get {
                return ResourceManager.GetString("Msg_InvalidStartTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified startup type is invalid. Options: Automatic, AutomaticDelayedStart, Manual, Disabled..
        /// </summary>
        public static string Msg_InvalidStartupType {
            get {
                return ResourceManager.GetString("Msg_InvalidStartupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified stderr file path is invalid..
        /// </summary>
        public static string Msg_InvalidStderrPath {
            get {
                return ResourceManager.GetString("Msg_InvalidStderrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified stdout file path is invalid..
        /// </summary>
        public static string Msg_InvalidStdoutPath {
            get {
                return ResourceManager.GetString("Msg_InvalidStdoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop timeout must be a number between {0} and {1} seconds..
        /// </summary>
        public static string Msg_InvalidStopTimeout {
            get {
                return ResourceManager.GetString("Msg_InvalidStopTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service wrapper executable not found..
        /// </summary>
        public static string Msg_InvalidWrapperExePath {
            get {
                return ResourceManager.GetString("Msg_InvalidWrapperExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords don&apos;t match..
        /// </summary>
        public static string Msg_PasswordsDontMatch {
            get {
                return ResourceManager.GetString("Msg_PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Exporting configurations to directory junctions or symlinks is prohibited to prevent path redirection attacks..
        /// </summary>
        public static string Msg_SecurityDirReparsePointExportProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityDirReparsePointExportProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Importing configurations through directory junctions or symlinks is prohibited to prevent path redirection attacks..
        /// </summary>
        public static string Msg_SecurityDirReparsePointProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityDirReparsePointProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Exporting configurations to file symbolic links or junctions is prohibited to prevent path redirection attacks..
        /// </summary>
        public static string Msg_SecurityFileReparsePointExportProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityFileReparsePointExportProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Importing configurations through file symbolic links or junctions is prohibited to prevent path redirection attacks..
        /// </summary>
        public static string Msg_SecurityFileReparsePointProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityFileReparsePointProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security: Could not obtain a SafeFileHandle for the target..
        /// </summary>
        public static string Msg_SecurityHandleInvalid {
            get {
                return ResourceManager.GetString("Msg_SecurityHandleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path validation failed at the kernel level: Kernel path resolution serialization failed..
        /// </summary>
        public static string Msg_SecurityHandleSerializationFailed {
            get {
                return ResourceManager.GetString("Msg_SecurityHandleSerializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path validation failed at the kernel level: Kernel size probe allocation failed..
        /// </summary>
        public static string Msg_SecurityHandleSizeProbeFailed {
            get {
                return ResourceManager.GetString("Msg_SecurityHandleSizeProbeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Guard Failure: Target file handle validation rejected. {0}.
        /// </summary>
        public static string Msg_SecurityHandleValidationFailed {
            get {
                return ResourceManager.GetString("Msg_SecurityHandleValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Invalid file type &apos;{0}&apos;. Only .json and .xml files are supported..
        /// </summary>
        public static string Msg_SecurityInvalidFileType {
            get {
                return ResourceManager.GetString("Msg_SecurityInvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Exporting to network drives (including mapped UNC shares) is prohibited..
        /// </summary>
        public static string Msg_SecurityNetworkDriveExportProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityNetworkDriveExportProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Importing from network drives (including mapped UNC shares) is prohibited..
        /// </summary>
        public static string Msg_SecurityNetworkDriveProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityNetworkDriveProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access Denied: The resolved path targets protected system directory &apos;{0}&apos;. Import prohibited..
        /// </summary>
        public static string Msg_SecurityProtectedDirectory {
            get {
                return ResourceManager.GetString("Msg_SecurityProtectedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access Denied: The resolved path targets protected system directory &apos;{0}&apos;. Export prohibited..
        /// </summary>
        public static string Msg_SecurityProtectedDirectoryExport {
            get {
                return ResourceManager.GetString("Msg_SecurityProtectedDirectoryExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: &apos;{0}&apos; is a reserved Windows device name and cannot be used..
        /// </summary>
        public static string Msg_SecurityReservedDeviceName {
            get {
                return ResourceManager.GetString("Msg_SecurityReservedDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Resolved file target points directly to a UNC destination. Import aborted..
        /// </summary>
        public static string Msg_SecurityResolvedUncDestination {
            get {
                return ResourceManager.GetString("Msg_SecurityResolvedUncDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Resolved file target points directly to a UNC destination. Export aborted..
        /// </summary>
        public static string Msg_SecurityResolvedUncDestinationExport {
            get {
                return ResourceManager.GetString("Msg_SecurityResolvedUncDestinationExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Exporting to UNC paths is prohibited to prevent configuration exfiltration..
        /// </summary>
        public static string Msg_SecurityUncPathExportProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityUncPathExportProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert: Importing from UNC paths is prohibited to prevent malicious configuration injection..
        /// </summary>
        public static string Msg_SecurityUncPathProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityUncPathProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was installed successfully..
        /// </summary>
        public static string Msg_ServiceInstalled {
            get {
                return ResourceManager.GetString("Msg_ServiceInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service name cannot have leading whitespace..
        /// </summary>
        public static string Msg_ServiceNameContainsLeadingWhitespace {
            get {
                return ResourceManager.GetString("Msg_ServiceNameContainsLeadingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service name cannot have trailing whitespace..
        /// </summary>
        public static string Msg_ServiceNameContainsTrailingWhitespace {
            get {
                return ResourceManager.GetString("Msg_ServiceNameContainsTrailingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service name exceeds {0} characters..
        /// </summary>
        public static string Msg_ServiceNameLengthReached {
            get {
                return ResourceManager.GetString("Msg_ServiceNameLengthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service name cannot be empty..
        /// </summary>
        public static string Msg_ServiceNameRequired {
            get {
                return ResourceManager.GetString("Msg_ServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was removed successfully..
        /// </summary>
        public static string Msg_ServiceRemoved {
            get {
                return ResourceManager.GetString("Msg_ServiceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was restarted successfully..
        /// </summary>
        public static string Msg_ServiceRestarted {
            get {
                return ResourceManager.GetString("Msg_ServiceRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was started successfully..
        /// </summary>
        public static string Msg_ServiceStarted {
            get {
                return ResourceManager.GetString("Msg_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was stopped successfully..
        /// </summary>
        public static string Msg_ServiceStopped {
            get {
                return ResourceManager.GetString("Msg_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Startup error: {0}.
        /// </summary>
        public static string Msg_StartupError_Format {
            get {
                return ResourceManager.GetString("Msg_StartupError_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occurred..
        /// </summary>
        public static string Msg_UnexpectedError {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occurred in the interface, but the application will attempt to continue. Details have been logged..
        /// </summary>
        public static string Msg_UnexpectedError_Body {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Servy - Unexpected Error.
        /// </summary>
        public static string Msg_UnexpectedError_Title {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please fill in all required fields..
        /// </summary>
        public static string Msg_ValidationError {
            get {
                return ResourceManager.GetString("Msg_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation passed for service &apos;{0}&apos;..
        /// </summary>
        public static string Msg_ValidationPassed {
            get {
                return ResourceManager.GetString("Msg_ValidationPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select process executable.
        /// </summary>
        public static string Title_SelectExecutable {
            get {
                return ResourceManager.GetString("Title_SelectExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select JSON file.
        /// </summary>
        public static string Title_SelectJson {
            get {
                return ResourceManager.GetString("Title_SelectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select startup directory.
        /// </summary>
        public static string Title_SelectStartupDirectory {
            get {
                return ResourceManager.GetString("Title_SelectStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select XML file.
        /// </summary>
        public static string Title_SelectXml {
            get {
                return ResourceManager.GetString("Title_SelectXml", resourceCulture);
            }
        }
    }
}
