//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.Manager.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.Manager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse All.
        /// </summary>
        public static string Button_CollapseAll {
            get {
                return ResourceManager.GetString("Button_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Configuration.
        /// </summary>
        public static string Button_Config {
            get {
                return ResourceManager.GetString("Button_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy PID.
        /// </summary>
        public static string Button_CopyPid {
            get {
                return ResourceManager.GetString("Button_CopyPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand All.
        /// </summary>
        public static string Button_ExpandAll {
            get {
                return ResourceManager.GetString("Button_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export JSON.
        /// </summary>
        public static string Button_ExportJSON {
            get {
                return ResourceManager.GetString("Button_ExportJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export XML.
        /// </summary>
        public static string Button_ExportXML {
            get {
                return ResourceManager.GetString("Button_ExportXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install.
        /// </summary>
        public static string Button_Install {
            get {
                return ResourceManager.GetString("Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More Actions.
        /// </summary>
        public static string Button_More {
            get {
                return ResourceManager.GetString("Button_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart.
        /// </summary>
        public static string Button_Restart {
            get {
                return ResourceManager.GetString("Button_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart Selected.
        /// </summary>
        public static string Button_RestartSelected {
            get {
                return ResourceManager.GetString("Button_RestartSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ▶ Resume.
        /// </summary>
        public static string Button_Resume {
            get {
                return ResourceManager.GetString("Button_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searching....
        /// </summary>
        public static string Button_Searching {
            get {
                return ResourceManager.GetString("Button_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Selected.
        /// </summary>
        public static string Button_StartSelected {
            get {
                return ResourceManager.GetString("Button_StartSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Selected.
        /// </summary>
        public static string Button_StopSelected {
            get {
                return ResourceManager.GetString("Button_StopSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Uninstall.
        /// </summary>
        public static string Button_Uninstall {
            get {
                return ResourceManager.GetString("Button_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CPU.
        /// </summary>
        public static string Column_CPU {
            get {
                return ResourceManager.GetString("Column_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Column_Description {
            get {
                return ResourceManager.GetString("Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        public static string Column_Level {
            get {
                return ResourceManager.GetString("Column_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log On As.
        /// </summary>
        public static string Column_LogOnAs {
            get {
                return ResourceManager.GetString("Column_LogOnAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        public static string Column_Message {
            get {
                return ResourceManager.GetString("Column_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Column_Name {
            get {
                return ResourceManager.GetString("Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PID.
        /// </summary>
        public static string Column_Pid {
            get {
                return ResourceManager.GetString("Column_Pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RAM.
        /// </summary>
        public static string Column_RAM {
            get {
                return ResourceManager.GetString("Column_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service.
        /// </summary>
        public static string Column_Service {
            get {
                return ResourceManager.GetString("Column_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Startup Type.
        /// </summary>
        public static string Column_StartupType {
            get {
                return ResourceManager.GetString("Column_StartupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Column_Status {
            get {
                return ResourceManager.GetString("Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time.
        /// </summary>
        public static string Column_Time {
            get {
                return ResourceManager.GetString("Column_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart selected services?.
        /// </summary>
        public static string Confirm_RestartSelectedServices {
            get {
                return ResourceManager.GetString("Confirm_RestartSelectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start selected services?.
        /// </summary>
        public static string Confirm_StartSelectedServices {
            get {
                return ResourceManager.GetString("Confirm_StartSelectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop selected services?.
        /// </summary>
        public static string Confirm_StopSelectedServices {
            get {
                return ResourceManager.GetString("Confirm_StopSelectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable service stdout/stderr redirection to live-monitor console output.
        /// </summary>
        public static string Console_Info {
            get {
                return ResourceManager.GetString("Console_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service dependency tree (via SCM).
        /// </summary>
        public static string Dependencies_Info {
            get {
                return ResourceManager.GetString("Dependencies_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON Configuration exported successfully..
        /// </summary>
        public static string ExportJson_Success {
            get {
                return ResourceManager.GetString("ExportJson_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML Configuration exported successfully..
        /// </summary>
        public static string ExportXml_Success {
            get {
                return ResourceManager.GetString("ExportXml_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Found {0} logs in {1}.
        /// </summary>
        public static string Footer_Log_Many {
            get {
                return ResourceManager.GetString("Footer_Log_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No logs found in {0}.
        /// </summary>
        public static string Footer_Log_None {
            get {
                return ResourceManager.GetString("Footer_Log_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Found 1 log in {0}.
        /// </summary>
        public static string Footer_Log_One {
            get {
                return ResourceManager.GetString("Footer_Log_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à log.
        /// </summary>
        public static string Footer_LogRowText {
            get {
                return ResourceManager.GetString("Footer_LogRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loaded {0} services in {1}.
        /// </summary>
        public static string Footer_Service_Many {
            get {
                return ResourceManager.GetString("Footer_Service_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No services loaded in {0}.
        /// </summary>
        public static string Footer_Service_None {
            get {
                return ResourceManager.GetString("Footer_Service_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loaded 1 service in {0}.
        /// </summary>
        public static string Footer_Service_One {
            get {
                return ResourceManager.GetString("Footer_Service_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à service.
        /// </summary>
        public static string Footer_ServiceRowText {
            get {
                return ResourceManager.GetString("Footer_ServiceRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to import JSON Configuration..
        /// </summary>
        public static string ImportJson_Error {
            get {
                return ResourceManager.GetString("ImportJson_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON Configuration imported successfully..
        /// </summary>
        public static string ImportJson_Success {
            get {
                return ResourceManager.GetString("ImportJson_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to import XML Configuration..
        /// </summary>
        public static string ImportXml_Error {
            get {
                return ResourceManager.GetString("ImportXml_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML Configuration imported successfully..
        /// </summary>
        public static string ImportXml_Success {
            get {
                return ResourceManager.GetString("ImportXml_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Console.
        /// </summary>
        public static string Label_ConsoleTab {
            get {
                return ResourceManager.GetString("Label_ConsoleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        public static string Label_Copy {
            get {
                return ResourceManager.GetString("Label_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CPU.
        /// </summary>
        public static string Label_CPU {
            get {
                return ResourceManager.GetString("Label_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status: Running (green), Stopped (red), Cycle (orange).
        /// </summary>
        public static string Label_Dependencies_Gear_Info {
            get {
                return ResourceManager.GetString("Label_Dependencies_Gear_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dependencies.
        /// </summary>
        public static string Label_DependenciesTab {
            get {
                return ResourceManager.GetString("Label_DependenciesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service statuses auto-refresh - Press F5 to refresh the full list.
        /// </summary>
        public static string Label_F5_Shortcut {
            get {
                return ResourceManager.GetString("Label_F5_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press F5 to refresh the dependency tree.
        /// </summary>
        public static string Label_F5_Shortcut_Dependencies {
            get {
                return ResourceManager.GetString("Label_F5_Shortcut_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press F5 to refresh logs.
        /// </summary>
        public static string Label_F5_Shortcut_Logs {
            get {
                return ResourceManager.GetString("Label_F5_Shortcut_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fetching....
        /// </summary>
        public static string Label_Fetching {
            get {
                return ResourceManager.GetString("Label_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à From:.
        /// </summary>
        public static string Label_From {
            get {
                return ResourceManager.GetString("Label_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyword:.
        /// </summary>
        public static string Label_Keyword {
            get {
                return ResourceManager.GetString("Label_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level:.
        /// </summary>
        public static string Label_Level {
            get {
                return ResourceManager.GetString("Label_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        public static string Label_LogsTab {
            get {
                return ResourceManager.GetString("Label_LogsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Performance.
        /// </summary>
        public static string Label_PerformanceTab {
            get {
                return ResourceManager.GetString("Label_PerformanceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PID.
        /// </summary>
        public static string Label_Pid {
            get {
                return ResourceManager.GetString("Label_Pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RAM.
        /// </summary>
        public static string Label_RAM {
            get {
                return ResourceManager.GetString("Label_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Services.
        /// </summary>
        public static string Label_ServicesTab {
            get {
                return ResourceManager.GetString("Label_ServicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To:.
        /// </summary>
        public static string Label_To {
            get {
                return ResourceManager.GetString("Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About Servy Manager.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check for updates....
        /// </summary>
        public static string Menu_CheckUpdates {
            get {
                return ResourceManager.GetString("Menu_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configurator.
        /// </summary>
        public static string Menu_Config {
            get {
                return ResourceManager.GetString("Menu_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help / Documentation.
        /// </summary>
        public static string Menu_Doc {
            get {
                return ResourceManager.GetString("Menu_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import JSON configuration.
        /// </summary>
        public static string Menu_ImportJson {
            get {
                return ResourceManager.GetString("Menu_ImportJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import XML configuration.
        /// </summary>
        public static string Menu_ImportXml {
            get {
                return ResourceManager.GetString("Menu_ImportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All operations failed..
        /// </summary>
        public static string Msg_AllOperationsFailed {
            get {
                return ResourceManager.GetString("Msg_AllOperationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arguments exceed the Windows command-line limit of {0} characters..
        /// </summary>
        public static string Msg_ArgumentsLengthReached {
            get {
                return ResourceManager.GetString("Msg_ArgumentsLengthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Servy Desktop App not found..
        /// </summary>
        public static string Msg_DesktopAppNotFound {
            get {
                return ResourceManager.GetString("Msg_DesktopAppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load service dependency tree..
        /// </summary>
        public static string Msg_FailedToLoadDependencyTree {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadDependencyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load JSON service configuration..
        /// </summary>
        public static string Msg_FailedToLoadJson {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load XML service configuration..
        /// </summary>
        public static string Msg_FailedToLoadXml {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid service name..
        /// </summary>
        public static string Msg_InvalidServiceName {
            get {
                return ResourceManager.GetString("Msg_InvalidServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service wrapper executable not found..
        /// </summary>
        public static string Msg_InvalidWrapperExePath {
            get {
                return ResourceManager.GetString("Msg_InvalidWrapperExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while switching tabs. Please try again..
        /// </summary>
        public static string Msg_MainTabControl_SelectionChangedError {
            get {
                return ResourceManager.GetString("Msg_MainTabControl_SelectionChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No services selected..
        /// </summary>
        public static string Msg_NoServicesSelected {
            get {
                return ResourceManager.GetString("Msg_NoServicesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation completed successfully..
        /// </summary>
        public static string Msg_OperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("Msg_OperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while performing the operation on: {0}.
        /// </summary>
        public static string Msg_OperationCompletedWithErrorsDetails {
            get {
                return ResourceManager.GetString("Msg_OperationCompletedWithErrorsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PID copied to clipboard..
        /// </summary>
        public static string Msg_PidCopied {
            get {
                return ResourceManager.GetString("Msg_PidCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to copy PID to clipboard..
        /// </summary>
        public static string Msg_PidCopyFailed {
            get {
                return ResourceManager.GetString("Msg_PidCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to remove this service? All service configuration will be permanently lost and cannot be recovered..
        /// </summary>
        public static string Msg_RemoveServiceConfirm {
            get {
                return ResourceManager.GetString("Msg_RemoveServiceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A service with this name already exists. Would you like to replace it?
        ///
        ///If the service is disabled and marked for deletion, the installation will fail until you restart your PC..
        /// </summary>
        public static string Msg_ServiceAlreadyExists {
            get {
                return ResourceManager.GetString("Msg_ServiceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified service is disabled..
        /// </summary>
        public static string Msg_ServiceDisabledError {
            get {
                return ResourceManager.GetString("Msg_ServiceDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was installed successfully..
        /// </summary>
        public static string Msg_ServiceInstalled {
            get {
                return ResourceManager.GetString("Msg_ServiceInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service not found..
        /// </summary>
        public static string Msg_ServiceNotFound {
            get {
                return ResourceManager.GetString("Msg_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was restarted successfully..
        /// </summary>
        public static string Msg_ServiceRestarted {
            get {
                return ResourceManager.GetString("Msg_ServiceRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was started successfully..
        /// </summary>
        public static string Msg_ServiceStarted {
            get {
                return ResourceManager.GetString("Msg_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was stopped successfully..
        /// </summary>
        public static string Msg_ServiceStopped {
            get {
                return ResourceManager.GetString("Msg_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occurred..
        /// </summary>
        public static string Msg_UnexpectedError {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to uninstall this service? All service configuration will be permanently lost and cannot be recovered..
        /// </summary>
        public static string Msg_UninstallServiceConfirm {
            get {
                return ResourceManager.GetString("Msg_UninstallServiceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export JSON configuration.
        /// </summary>
        public static string SaveFileDialog_JsonTitle {
            get {
                return ResourceManager.GetString("SaveFileDialog_JsonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export XML configuration.
        /// </summary>
        public static string SaveFileDialog_XmlTitle {
            get {
                return ResourceManager.GetString("SaveFileDialog_XmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Servy Manager requires administrative privileges to manage system services..
        /// </summary>
        public static string SecurityWarningMessage {
            get {
                return ResourceManager.GetString("SecurityWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elevation Required.
        /// </summary>
        public static string SecurityWarningTitle {
            get {
                return ResourceManager.GetString("SecurityWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading Servy Manager....
        /// </summary>
        public static string Splash_Text {
            get {
                return ResourceManager.GetString("Splash_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Critical Security Risk: Your system is using an outdated SQLite engine ({0}). This version of the application requires SQLite {1} or higher to mitigate CVE-2025-6965..
        /// </summary>
        public static string SqliteVersionWarningMessage {
            get {
                return ResourceManager.GetString("SqliteVersionWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert.
        /// </summary>
        public static string SqliteVersionWarningTitle {
            get {
                return ResourceManager.GetString("SqliteVersionWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic.
        /// </summary>
        public static string StartupType_Automatic {
            get {
                return ResourceManager.GetString("StartupType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic (delayed).
        /// </summary>
        public static string StartupType_AutomaticDelayedStart {
            get {
                return ResourceManager.GetString("StartupType_AutomaticDelayedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        public static string StartupType_Disabled {
            get {
                return ResourceManager.GetString("StartupType_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manual.
        /// </summary>
        public static string StartupType_Manual {
            get {
                return ResourceManager.GetString("StartupType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown.
        /// </summary>
        public static string StartupType_Unknown {
            get {
                return ResourceManager.GetString("StartupType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue Pending.
        /// </summary>
        public static string Status_ContinuePending {
            get {
                return ResourceManager.GetString("Status_ContinuePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not Installed.
        /// </summary>
        public static string Status_NotInstalled {
            get {
                return ResourceManager.GetString("Status_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paused.
        /// </summary>
        public static string Status_Paused {
            get {
                return ResourceManager.GetString("Status_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause Pending.
        /// </summary>
        public static string Status_PausePending {
            get {
                return ResourceManager.GetString("Status_PausePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Running.
        /// </summary>
        public static string Status_Running {
            get {
                return ResourceManager.GetString("Status_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Pending.
        /// </summary>
        public static string Status_StartPending {
            get {
                return ResourceManager.GetString("Status_StartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stopped.
        /// </summary>
        public static string Status_Stopped {
            get {
                return ResourceManager.GetString("Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Pending.
        /// </summary>
        public static string Status_StopPending {
            get {
                return ResourceManager.GetString("Status_StopPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///Servy Manager {0}
        ///
        ///Servy Manager provides a clean and simple interface for managing Windows services created with Servy. Start, stop, configure, and monitor services with ease.
        ///
        ///Built with {1}
        ///
        ///Licensed under the MIT License.
        ///
        ///Copyright © {2} Akram El Assas. All rights reserved.
        ///    .
        /// </summary>
        public static string Text_About {
            get {
                return ResourceManager.GetString("Text_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse all nodes in the dependency tree.
        /// </summary>
        public static string Tooltip_CollapseAll {
            get {
                return ResourceManager.GetString("Tooltip_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Circular dependency detected.
        /// </summary>
        public static string Tooltip_Cycle {
            get {
                return ResourceManager.GetString("Tooltip_Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand all nodes in the dependency tree.
        /// </summary>
        public static string Tooltip_ExpandAll {
            get {
                return ResourceManager.GetString("Tooltip_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh the service dependency tree.
        /// </summary>
        public static string Tooltip_Refresh {
            get {
                return ResourceManager.GetString("Tooltip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resume live updates.
        /// </summary>
        public static string Tooltip_Resume {
            get {
                return ResourceManager.GetString("Tooltip_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This service is running.
        /// </summary>
        public static string Tooltip_ServiceRunning {
            get {
                return ResourceManager.GetString("Tooltip_ServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This service is stopped.
        /// </summary>
        public static string Tooltip_ServiceStopped {
            get {
                return ResourceManager.GetString("Tooltip_ServiceStopped", resourceCulture);
            }
        }
    }
}
