//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.UI.Resources
{
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to open the documentation. Please ensure a web browser is installed. Details: {0}.
        /// </summary>
        public static string Msg_DocumentationOpenFailed {
            get {
                return ResourceManager.GetString("Msg_DocumentationOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed copying embedded resource: {0}.
        /// </summary>
        public static string Msg_FailedCopyingEmbeddedResource_Format {
            get {
                return ResourceManager.GetString("Msg_FailedCopyingEmbeddedResource_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified path is invalid..
        /// </summary>
        public static string Msg_InvalidPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No updates currently available..
        /// </summary>
        public static string Msg_NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("Msg_NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new version of Servy is available. Do you want to download it?.
        /// </summary>
        public static string Msg_UpdateAvailablePrompt {
            get {
                return ResourceManager.GetString("Msg_UpdateAvailablePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to check updates: {0}.
        /// </summary>
        public static string Msg_UpdateCheckFailed {
            get {
                return ResourceManager.GetString("Msg_UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The update check completed successfully, but the latest release identifier format could not be processed safely: &apos;{0}&apos;. Please inspect the project release page manually..
        /// </summary>
        public static string Msg_UpdateCheckInvalidTag {
            get {
                return ResourceManager.GetString("Msg_UpdateCheckInvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The update check timed out. Please try again later..
        /// </summary>
        public static string Msg_UpdateCheckTimeout {
            get {
                return ResourceManager.GetString("Msg_UpdateCheckTimeout", resourceCulture);
            }
        }
    }
}
