using Moq;
using Servy.Manager.Models;
using Servy.Manager.Services;
using Servy.Manager.ViewModels;
using Servy.Manager.Views;
using Servy.Testing;
using Servy.UI.Services;
using System.Windows;

namespace Servy.Manager.UnitTests.Views
{
    /// <summary>
    /// A simple concrete implementation of the abstract ServiceSearchUserControl 
    /// used to safely isolate and test the shared baseline behavior.
    /// </summary>
    public class TestServiceSearchUserControl : ServiceSearchUserControl
    {
        public const string ExpectedViewName = "TestSearchView";

        protected override string ViewName => ExpectedViewName;
    }

    [Collection("Ambient AppServices Dependent Tests")]
    public class ServiceSearchUserControlTests
    {
        /// <summary>
        /// Concrete View-Model stub inheriting from ServiceSearchViewModelBase to serve as DataContext.
        /// Correctly forwards mock dependencies to the base class and adheres to BulkObservableCollection rules.
        /// </summary>
        private class TestServiceSearchViewModel : ServiceSearchViewModelBase
        {
            public bool ExecuteAsyncWasCalled { get; private set; }
            public TaskCompletionSource<object?> CommandTcs { get; } = new TaskCompletionSource<object?>();

            public TestServiceSearchViewModel(
                ICursorService cursorService,
                IUiDispatcher uiDispatcher,
                IServiceCommands serviceCommands)
                : base(cursorService, uiDispatcher, serviceCommands)
            {
                // Override the default SearchCommand generated by the base constructor 
                // to monitor execution branches inside our unit tests
                SearchCommand = new UI.Commands.AsyncCommand(async (param) =>
                {
                    ExecuteAsyncWasCalled = true;
                    await CommandTcs.Task;
                }, name: "TestSearchCommand");
            }

            /// <summary>
            /// Simple mock implementation of the required abstract base map routine.
            /// </summary>
            protected override ServiceItemBase CreateServiceItem(Service? service)
            {
                return new DependencyService { Name = service?.Name };
            }
        }

        private readonly Mock<ICursorService> _mockCursorService = new Mock<ICursorService>();
        private readonly Mock<IUiDispatcher> _mockUiDispatcher = new Mock<IUiDispatcher>();
        private readonly Mock<IServiceCommands> _mockServiceCommands = new Mock<IServiceCommands>();

        private TestServiceSearchViewModel CreateIsolatedViewModel()
        {
            return new TestServiceSearchViewModel(
                _mockCursorService.Object,
                _mockUiDispatcher.Object,
                _mockServiceCommands.Object);
        }

        /// <summary>
        /// Centralized, non-blocking polling primitive helper to track asynchronous fire-and-forget processing blocks safely.
        /// </summary>
        private static async Task PollUntilTrueAsync(Func<bool> condition, int maxRetries = 25, int delayMs = 20)
        {
            int retries = 0;
            while (!condition() && retries < maxRetries)
            {
                await Task.Delay(delayMs);
                retries++;
            }
        }

        [Fact]
        public async Task UserControl_Loaded_WhenDataContextIsNull_DoesNotThrowAndCompletesSilently()
        {
            await Helper.RunOnSTA(async () =>
            {
                // Arrange
                var control = new TestServiceSearchUserControl();
                control.DataContext = null;

                // Act & Assert
                var exception = Record.Exception(() =>
                    control.RaiseEvent(new RoutedEventArgs(FrameworkElement.LoadedEvent)));

                Assert.Null(exception);
                await Task.CompletedTask;
            }, createApp: true);
        }

        [Fact]
        public async Task UserControl_Loaded_WhenServicesAlreadyExist_SkipsRedundantSearchCommandExecution()
        {
            await Helper.RunOnSTA(async () =>
            {
                // Arrange
                var control = new TestServiceSearchUserControl();
                var viewModel = CreateIsolatedViewModel();

                // Add a dummy entry directly to the read-only bulk collection properties block
                viewModel.Services.Add(new DependencyService { Name = "ExistingService" });
                control.DataContext = viewModel;

                // Act
                control.RaiseEvent(new RoutedEventArgs(FrameworkElement.LoadedEvent));
                await Task.Delay(50);

                // Assert
                Assert.False(viewModel.ExecuteAsyncWasCalled);
            }, createApp: true);
        }

        [Fact]
        public async Task UserControl_Loaded_WhenServicesAreEmpty_ExecutesInitialSearchCommandSuccessfully()
        {
            await Helper.RunOnSTA(async () =>
            {
                // Arrange
                var control = new TestServiceSearchUserControl();
                var viewModel = CreateIsolatedViewModel();

                viewModel.Services.Clear(); // Collection state evaluates to !Any()
                control.DataContext = viewModel;

                // Act
                control.RaiseEvent(new RoutedEventArgs(FrameworkElement.LoadedEvent));
                viewModel.CommandTcs.SetResult(null);

                // Centralized poll tracking handles asynchronous execution window
                await PollUntilTrueAsync(() => viewModel.ExecuteAsyncWasCalled);

                // Assert
                Assert.True(viewModel.ExecuteAsyncWasCalled);
            }, createApp: true);
        }

        [Fact]
        public async Task UserControl_Loaded_WhenOperationIsCanceled_CatchesExceptionAndHandlesGracefully()
        {
            await Helper.RunOnSTA(async () =>
            {
                // Arrange
                var control = new TestServiceSearchUserControl();
                var viewModel = CreateIsolatedViewModel();
                control.DataContext = viewModel;

                // Act
                control.RaiseEvent(new RoutedEventArgs(FrameworkElement.LoadedEvent));
                viewModel.CommandTcs.SetException(new OperationCanceledException());

                // Centralized poll tracking handles asynchronous execution window
                await PollUntilTrueAsync(() => viewModel.ExecuteAsyncWasCalled);

                // Assert
                Assert.True(viewModel.ExecuteAsyncWasCalled);
            }, createApp: true);
        }

        [Fact]
        public async Task UserControl_Loaded_WhenGenericExceptionIsThrown_LogsErrorContextAndDoesNotCrashProcess()
        {
            await Helper.RunOnSTA(async () =>
            {
                // Arrange
                var control = new TestServiceSearchUserControl();
                var viewModel = CreateIsolatedViewModel();
                control.DataContext = viewModel;

                // Act
                control.RaiseEvent(new RoutedEventArgs(FrameworkElement.LoadedEvent));
                viewModel.CommandTcs.SetException(new InvalidOperationException("SCM Connection Refused"));

                // Centralized poll tracking handles asynchronous execution window
                await PollUntilTrueAsync(() => viewModel.ExecuteAsyncWasCalled);

                // Give the internal Logger line a single dispatch sequence loop to write out traces cleanly
                await Task.Delay(30);

                // Assert
                Assert.True(viewModel.ExecuteAsyncWasCalled);
            }, createApp: true);
        }
    }
}