//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        public static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install.
        /// </summary>
        public static string Button_Install {
            get {
                return ResourceManager.GetString("Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart.
        /// </summary>
        public static string Button_Restart {
            get {
                return ResourceManager.GetString("Button_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Uninstall.
        /// </summary>
        public static string Button_Uninstall {
            get {
                return ResourceManager.GetString("Button_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to clear all configuration values?.
        /// </summary>
        public static string Confirm_ClearAll {
            get {
                return ResourceManager.GetString("Confirm_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily (default).
        /// </summary>
        public static string DateRotationType_Daily {
            get {
                return ResourceManager.GetString("DateRotationType_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monthly.
        /// </summary>
        public static string DateRotationType_Monthly {
            get {
                return ResourceManager.GetString("DateRotationType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        public static string DateRotationType_None {
            get {
                return ResourceManager.GetString("DateRotationType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weekly.
        /// </summary>
        public static string DateRotationType_Weekly {
            get {
                return ResourceManager.GetString("DateRotationType_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select standard error file.
        /// </summary>
        public static string Dialog_SelectStderrFile {
            get {
                return ResourceManager.GetString("Dialog_SelectStderrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select standard output file.
        /// </summary>
        public static string Dialog_SelectStdoutFile {
            get {
                return ResourceManager.GetString("Dialog_SelectStdoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON Configuration exported successfully..
        /// </summary>
        public static string ExportJson_Success {
            get {
                return ResourceManager.GetString("ExportJson_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML Configuration exported successfully..
        /// </summary>
        public static string ExportXml_Success {
            get {
                return ResourceManager.GetString("ExportXml_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When both size-based and date-based rotation are enabled, size rotation takes precedence..
        /// </summary>
        public static string Info_DateRotation {
            get {
                return ResourceManager.GetString("Info_DateRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When enabled, environment variables and process parameters are recorded in the Servy.Service.log file. Not recommended for production environments, as these logs may contain sensitive information..
        /// </summary>
        public static string Info_EnableDebugLogs {
            get {
                return ResourceManager.GetString("Info_EnableDebugLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter variables in the format varName=varValue, one per line or separated by semicolons (;). Use \= to escape &apos;=&apos;, \&quot; to escape &apos;&quot;&apos;, \; to escape &apos;;&apos;, \\ to escape &apos;\&apos;, and %% to escape &apos;%&apos; (collapses to a single &apos;%&apos;). Supports environment variable expansion, example: VAR1=%ProgramData%\MyApp; VAR2=%VAR1%\bin.
        /// </summary>
        public static string Info_EnvironmentVariables {
            get {
                return ResourceManager.GetString("Info_EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure a script or executable to run when the process fails to start. If health monitoring is disabled, the program will run when the process fails to start. If health monitoring is enabled, the program will only run after all configured recovery action retries have failed..
        /// </summary>
        public static string Info_FailureProgram {
            get {
                return ResourceManager.GetString("Info_FailureProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optional. If not set, defaults to the service working directory..
        /// </summary>
        public static string Info_FailureProgramStartupDirectory {
            get {
                return ResourceManager.GetString("Info_FailureProgramStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set to 0 for unlimited restart attempts..
        /// </summary>
        public static string Info_MaxRestartAttempts {
            get {
                return ResourceManager.GetString("Info_MaxRestartAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum rotated log files to keep. Set to 0 for unlimited..
        /// </summary>
        public static string Info_MaxRotations {
            get {
                return ResourceManager.GetString("Info_MaxRotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure an optional script or executable to run after the process starts successfully..
        /// </summary>
        public static string Info_PostLaunch {
            get {
                return ResourceManager.GetString("Info_PostLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optional. If not set, defaults to the service working directory..
        /// </summary>
        public static string Info_PostLaunchStartupDirectory {
            get {
                return ResourceManager.GetString("Info_PostLaunchStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure an optional script or executable to run after the wrapped process and all of its child processes have exited. The post-stop process is started in fire-and-forget mode and does not block service shutdown..
        /// </summary>
        public static string Info_PostStop {
            get {
                return ResourceManager.GetString("Info_PostStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optional. If not set, defaults to the service working directory..
        /// </summary>
        public static string Info_PostStopStartupDirectory {
            get {
                return ResourceManager.GetString("Info_PostStopStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optional script to run before service start. If it fails, the service won&apos;t start unless Ignore Failure is enabled..
        /// </summary>
        public static string Info_PreLaunch {
            get {
                return ResourceManager.GetString("Info_PreLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optional. If not set, defaults to the service working directory..
        /// </summary>
        public static string Info_PreLaunchStartupDirectory {
            get {
                return ResourceManager.GetString("Info_PreLaunchStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the timeout to 0 to run in fire-and-forget mode (disables retries and logging)..
        /// </summary>
        public static string Info_PreLaunchTimeout {
            get {
                return ResourceManager.GetString("Info_PreLaunchTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure an optional script or executable to run before the main service stops. Use it for graceful shutdown tasks such as notifying external systems or draining resources. The pre-stop process runs synchronously and extends the service stop timeout while running, unless the timeout is set to 0..
        /// </summary>
        public static string Info_PreStop {
            get {
                return ResourceManager.GetString("Info_PreStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optional. If not set, defaults to the service working directory..
        /// </summary>
        public static string Info_PreStopStartupDirectory {
            get {
                return ResourceManager.GetString("Info_PreStopStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the timeout to 0 to run in fire-and-forget mode..
        /// </summary>
        public static string Info_PreStopTimeout {
            get {
                return ResourceManager.GetString("Info_PreStopTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process parameters support environment variable expansion. Example:
        ///--param=&quot;%ProgramData%\MyApp&quot; --param=&quot;%MY_VAR%\bin&quot;.
        /// </summary>
        public static string Info_ProcessParameters {
            get {
                return ResourceManager.GetString("Info_ProcessParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supports environment variable expansion, example: %JAVA_HOME%\bin\java.exe.
        /// </summary>
        public static string Info_ProcessPath {
            get {
                return ResourceManager.GetString("Info_ProcessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart service and restart computer actions are not available if the service runs under NT AUTHORITY\NetworkService, NT AUTHORITY\LocalService, or a user account without the required privileges. Only the restart process action will be available for these accounts..
        /// </summary>
        public static string Info_RecoveryAction {
            get {
                return ResourceManager.GetString("Info_RecoveryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run recovery action even if the process exits successfully..
        /// </summary>
        public static string Info_RecoveryOnCleanExit {
            get {
                return ResourceManager.GetString("Info_RecoveryOnCleanExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify one or more Windows service names (not display names) that this service depends on. Enter each service name on a new line or separate them with semicolons (;). Use service key names without spaces or special characters. Each dependency service must be installed and running before this service can start. If a dependency&apos;s start type is Automatic, Windows will try to start it automatically before this service. If a dependency fails to start or is disabled, this service will not start..
        /// </summary>
        public static string Info_ServiceDependencies {
            get {
                return ResourceManager.GetString("Info_ServiceDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The human-readable name shown in the Windows Services console (services.msc). If left empty, the service name will be used instead..
        /// </summary>
        public static string Info_ServiceDisplayName {
            get {
                return ResourceManager.GetString("Info_ServiceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The timeout in seconds to wait for the process to start successfully before considering the startup as failed..
        /// </summary>
        public static string Info_StartTimeout {
            get {
                return ResourceManager.GetString("Info_StartTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supports environment variable expansion, example: %PROGRAMDATA%\MyApp.
        /// </summary>
        public static string Info_StartupDirectory {
            get {
                return ResourceManager.GetString("Info_StartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The timeout in seconds to wait for the process to exit..
        /// </summary>
        public static string Info_StopTimeout {
            get {
                return ResourceManager.GetString("Info_StopTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The service account username (e.g., .\username, DOMAIN\username, or DOMAIN\gMSA$)..
        /// </summary>
        public static string Info_UserAccount {
            get {
                return ResourceManager.GetString("Info_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the service runs under an account other than Local System, you must grant write access to %ProgramData%\Servy for the account that runs the service..
        /// </summary>
        public static string Info_UserAccountRights {
            get {
                return ResourceManager.GetString("Info_UserAccountRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced.
        /// </summary>
        public static string Label_AdvancedTab {
            get {
                return ResourceManager.GetString("Label_AdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à attempts.
        /// </summary>
        public static string Label_Attempts {
            get {
                return ResourceManager.GetString("Label_Attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm Password.
        /// </summary>
        public static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Rotation Interval.
        /// </summary>
        public static string Label_DateRotationType {
            get {
                return ResourceManager.GetString("Label_DateRotationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Console UI (for interactive console apps; disables stdout/stderr redirection).
        /// </summary>
        public static string Label_EnableConsoleUI {
            get {
                return ResourceManager.GetString("Label_EnableConsoleUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable date-based Rotation.
        /// </summary>
        public static string Label_EnableDateRotation {
            get {
                return ResourceManager.GetString("Label_EnableDateRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Debug Logs.
        /// </summary>
        public static string Label_EnableDebugLogs {
            get {
                return ResourceManager.GetString("Label_EnableDebugLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Health Monitoring.
        /// </summary>
        public static string Label_EnableHealthMonitoring {
            get {
                return ResourceManager.GetString("Label_EnableHealthMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable size-based Rotation.
        /// </summary>
        public static string Label_EnableSizeRotation {
            get {
                return ResourceManager.GetString("Label_EnableSizeRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Environment Variables.
        /// </summary>
        public static string Label_EnvironmentVariables {
            get {
                return ResourceManager.GetString("Label_EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heartbeat Interval.
        /// </summary>
        public static string Label_HeartbeatInterval {
            get {
                return ResourceManager.GetString("Label_HeartbeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logging.
        /// </summary>
        public static string Label_LoggingTab {
            get {
                return ResourceManager.GetString("Label_LoggingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log On.
        /// </summary>
        public static string Label_LogOnTab {
            get {
                return ResourceManager.GetString("Label_LogOnTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main.
        /// </summary>
        public static string Label_MainTab {
            get {
                return ResourceManager.GetString("Label_MainTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max Failed Checks.
        /// </summary>
        public static string Label_MaxFailedChecks {
            get {
                return ResourceManager.GetString("Label_MaxFailedChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max Restart Attempts.
        /// </summary>
        public static string Label_MaxRestartAttempts {
            get {
                return ResourceManager.GetString("Label_MaxRestartAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max Rotations.
        /// </summary>
        public static string Label_MaxRotations {
            get {
                return ResourceManager.GetString("Label_MaxRotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post-Launch.
        /// </summary>
        public static string Label_PostLaunchTab {
            get {
                return ResourceManager.GetString("Label_PostLaunchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post-Stop.
        /// </summary>
        public static string Label_PostStopTab {
            get {
                return ResourceManager.GetString("Label_PostStopTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore Failure.
        /// </summary>
        public static string Label_PreLaunchIgnoreFailure {
            get {
                return ResourceManager.GetString("Label_PreLaunchIgnoreFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retry Attempts.
        /// </summary>
        public static string Label_PreLaunchRetryAttempts {
            get {
                return ResourceManager.GetString("Label_PreLaunchRetryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pre-Launch.
        /// </summary>
        public static string Label_PreLaunchTab {
            get {
                return ResourceManager.GetString("Label_PreLaunchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout.
        /// </summary>
        public static string Label_PreLaunchTimeoutSeconds {
            get {
                return ResourceManager.GetString("Label_PreLaunchTimeoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log pre-stop failure as error.
        /// </summary>
        public static string Label_PreStopLogAsError {
            get {
                return ResourceManager.GetString("Label_PreStopLogAsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pre-Stop.
        /// </summary>
        public static string Label_PreStopTab {
            get {
                return ResourceManager.GetString("Label_PreStopTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout.
        /// </summary>
        public static string Label_PreStopTimeoutSeconds {
            get {
                return ResourceManager.GetString("Label_PreStopTimeoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process Parameters.
        /// </summary>
        public static string Label_ProcessParameters {
            get {
                return ResourceManager.GetString("Label_ProcessParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process Path *.
        /// </summary>
        public static string Label_ProcessPath {
            get {
                return ResourceManager.GetString("Label_ProcessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process Path.
        /// </summary>
        public static string Label_ProcessPathNotRequired {
            get {
                return ResourceManager.GetString("Label_ProcessPathNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process Priority.
        /// </summary>
        public static string Label_ProcessPriority {
            get {
                return ResourceManager.GetString("Label_ProcessPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery Action.
        /// </summary>
        public static string Label_RecoveryAction {
            get {
                return ResourceManager.GetString("Label_RecoveryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery even on successful exit.
        /// </summary>
        public static string Label_RecoveryOnCleanExit {
            get {
                return ResourceManager.GetString("Label_RecoveryOnCleanExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery.
        /// </summary>
        public static string Label_RecoveryTab {
            get {
                return ResourceManager.GetString("Label_RecoveryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à * Required fields.
        /// </summary>
        public static string Label_RequiredFields {
            get {
                return ResourceManager.GetString("Label_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotation Size.
        /// </summary>
        public static string Label_RotationSize {
            get {
                return ResourceManager.GetString("Label_RotationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Megabytes (MB).
        /// </summary>
        public static string Label_RotationSizeUnit {
            get {
                return ResourceManager.GetString("Label_RotationSizeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run As Local System.
        /// </summary>
        public static string Label_RunAsLocalSystem {
            get {
                return ResourceManager.GetString("Label_RunAsLocalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seconds.
        /// </summary>
        public static string Label_Seconds {
            get {
                return ResourceManager.GetString("Label_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service Dependencies.
        /// </summary>
        public static string Label_ServiceDependencies {
            get {
                return ResourceManager.GetString("Label_ServiceDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service Description.
        /// </summary>
        public static string Label_ServiceDescription {
            get {
                return ResourceManager.GetString("Label_ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display Name.
        /// </summary>
        public static string Label_ServiceDisplayName {
            get {
                return ResourceManager.GetString("Label_ServiceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service Name *.
        /// </summary>
        public static string Label_ServiceName {
            get {
                return ResourceManager.GetString("Label_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Timeout.
        /// </summary>
        public static string Label_StartTimeout {
            get {
                return ResourceManager.GetString("Label_StartTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Startup Directory.
        /// </summary>
        public static string Label_StartupDirectory {
            get {
                return ResourceManager.GetString("Label_StartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Startup Type.
        /// </summary>
        public static string Label_StartupType {
            get {
                return ResourceManager.GetString("Label_StartupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stderr File Path.
        /// </summary>
        public static string Label_StderrPath {
            get {
                return ResourceManager.GetString("Label_StderrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stdout File Path.
        /// </summary>
        public static string Label_StdoutPath {
            get {
                return ResourceManager.GetString("Label_StdoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Timeout.
        /// </summary>
        public static string Label_StopTimeout {
            get {
                return ResourceManager.GetString("Label_StopTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use local time for log rotation (Default: UTC).
        /// </summary>
        public static string Label_UseLocalTimeForRotation {
            get {
                return ResourceManager.GetString("Label_UseLocalTimeForRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Account.
        /// </summary>
        public static string Label_UserAccount {
            get {
                return ResourceManager.GetString("Label_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About Servy.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check for updates....
        /// </summary>
        public static string Menu_CheckUpdates {
            get {
                return ResourceManager.GetString("Menu_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear All.
        /// </summary>
        public static string Menu_ClearAll {
            get {
                return ResourceManager.GetString("Menu_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help / Documentation.
        /// </summary>
        public static string Menu_Doc {
            get {
                return ResourceManager.GetString("Menu_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export JSON configuration.
        /// </summary>
        public static string Menu_ExportJson {
            get {
                return ResourceManager.GetString("Menu_ExportJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export XML configuration.
        /// </summary>
        public static string Menu_ExportXml {
            get {
                return ResourceManager.GetString("Menu_ExportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import JSON configuration.
        /// </summary>
        public static string Menu_ImportJson {
            get {
                return ResourceManager.GetString("Menu_ImportJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import XML configuration.
        /// </summary>
        public static string Menu_ImportXml {
            get {
                return ResourceManager.GetString("Menu_ImportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manager.
        /// </summary>
        public static string Menu_Manager {
            get {
                return ResourceManager.GetString("Menu_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrator privileges are required..
        /// </summary>
        public static string Msg_AdminRightsRequired {
            get {
                return ResourceManager.GetString("Msg_AdminRightsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arguments exceed the Windows command-line limit of {0} characters..
        /// </summary>
        public static string Msg_ArgumentsLengthReached {
            get {
                return ResourceManager.GetString("Msg_ArgumentsLengthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load JSON service configuration..
        /// </summary>
        public static string Msg_FailedToLoadJson {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load XML service configuration..
        /// </summary>
        public static string Msg_FailedToLoadXml {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service wrapper executable not found..
        /// </summary>
        public static string Msg_InvalidWrapperExePath {
            get {
                return ResourceManager.GetString("Msg_InvalidWrapperExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to launch the Manager application..
        /// </summary>
        public static string Msg_ManagerAppLaunchFailed {
            get {
                return ResourceManager.GetString("Msg_ManagerAppLaunchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Servy Manager App not found..
        /// </summary>
        public static string Msg_ManagerAppNotFound {
            get {
                return ResourceManager.GetString("Msg_ManagerAppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords don&apos;t match..
        /// </summary>
        public static string Msg_PasswordsDontMatch {
            get {
                return ResourceManager.GetString("Msg_PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A service with this name already exists. Would you like to replace it?
        ///
        ///If the service is disabled and marked for deletion, the installation will fail until you restart your PC..
        /// </summary>
        public static string Msg_ServiceAlreadyExists {
            get {
                return ResourceManager.GetString("Msg_ServiceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified service is disabled..
        /// </summary>
        public static string Msg_ServiceDisabledError {
            get {
                return ResourceManager.GetString("Msg_ServiceDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was installed successfully..
        /// </summary>
        public static string Msg_ServiceInstalled {
            get {
                return ResourceManager.GetString("Msg_ServiceInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A service name is required to perform this action..
        /// </summary>
        public static string Msg_ServiceNameError {
            get {
                return ResourceManager.GetString("Msg_ServiceNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified service was not found..
        /// </summary>
        public static string Msg_ServiceNotFound {
            get {
                return ResourceManager.GetString("Msg_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was removed successfully..
        /// </summary>
        public static string Msg_ServiceRemoved {
            get {
                return ResourceManager.GetString("Msg_ServiceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was restarted successfully..
        /// </summary>
        public static string Msg_ServiceRestarted {
            get {
                return ResourceManager.GetString("Msg_ServiceRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was started successfully..
        /// </summary>
        public static string Msg_ServiceStarted {
            get {
                return ResourceManager.GetString("Msg_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service was stopped successfully..
        /// </summary>
        public static string Msg_ServiceStopped {
            get {
                return ResourceManager.GetString("Msg_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occurred..
        /// </summary>
        public static string Msg_UnexpectedError {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Above Normal.
        /// </summary>
        public static string ProcessPriority_AboveNormal {
            get {
                return ResourceManager.GetString("ProcessPriority_AboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Below Normal.
        /// </summary>
        public static string ProcessPriority_BelowNormal {
            get {
                return ResourceManager.GetString("ProcessPriority_BelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High.
        /// </summary>
        public static string ProcessPriority_High {
            get {
                return ResourceManager.GetString("ProcessPriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Idle.
        /// </summary>
        public static string ProcessPriority_Idle {
            get {
                return ResourceManager.GetString("ProcessPriority_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal (default).
        /// </summary>
        public static string ProcessPriority_Normal {
            get {
                return ResourceManager.GetString("ProcessPriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real Time (use with caution).
        /// </summary>
        public static string ProcessPriority_RealTime {
            get {
                return ResourceManager.GetString("ProcessPriority_RealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        public static string RecoveryAction_None {
            get {
                return ResourceManager.GetString("RecoveryAction_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart Computer.
        /// </summary>
        public static string RecoveryAction_RestartComputer {
            get {
                return ResourceManager.GetString("RecoveryAction_RestartComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart Process.
        /// </summary>
        public static string RecoveryAction_RestartProcess {
            get {
                return ResourceManager.GetString("RecoveryAction_RestartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart Service (default).
        /// </summary>
        public static string RecoveryAction_RestartService {
            get {
                return ResourceManager.GetString("RecoveryAction_RestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export JSON configuration.
        /// </summary>
        public static string SaveFileDialog_JsonTitle {
            get {
                return ResourceManager.GetString("SaveFileDialog_JsonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export XML configuration.
        /// </summary>
        public static string SaveFileDialog_XmlTitle {
            get {
                return ResourceManager.GetString("SaveFileDialog_XmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Servy requires administrative privileges to manage system services..
        /// </summary>
        public static string SecurityWarningMessage {
            get {
                return ResourceManager.GetString("SecurityWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elevation Required.
        /// </summary>
        public static string SecurityWarningTitle {
            get {
                return ResourceManager.GetString("SecurityWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading Servy....
        /// </summary>
        public static string Splash_Text {
            get {
                return ResourceManager.GetString("Splash_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Critical Security Risk: Your system is using an outdated SQLite engine ({0}). This version of the application requires SQLite {1} or higher to mitigate CVE-2025-6965..
        /// </summary>
        public static string SqliteVersionWarningMessage {
            get {
                return ResourceManager.GetString("SqliteVersionWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security Alert.
        /// </summary>
        public static string SqliteVersionWarningTitle {
            get {
                return ResourceManager.GetString("SqliteVersionWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic (default).
        /// </summary>
        public static string StartupType_Automatic {
            get {
                return ResourceManager.GetString("StartupType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic (delayed start).
        /// </summary>
        public static string StartupType_AutomaticDelayedStart {
            get {
                return ResourceManager.GetString("StartupType_AutomaticDelayedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        public static string StartupType_Disabled {
            get {
                return ResourceManager.GetString("StartupType_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manual.
        /// </summary>
        public static string StartupType_Manual {
            get {
                return ResourceManager.GetString("StartupType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///Servy {0}
        ///
        ///Servy lets you run any application as a native Windows service, with full control over its working directory, startup behavior, logging, health checks, and recovery options.
        ///
        ///It includes a desktop app, a CLI, and a PowerShell module, letting you manage services manually or automate everything in scripts and CI/CD pipelines.
        ///
        ///Built with {1}
        ///
        ///Licensed under the MIT License.
        ///
        ///Copyright © {2} Akram El Assas. All rights reserved.
        ///    .
        /// </summary>
        public static string Text_About {
            get {
                return ResourceManager.GetString("Text_About", resourceCulture);
            }
        }
    }
}
